services:
  - type: web
    name: skylearn-web
    env: python
    pythonVersion: 3.11
    buildCommand: pip install -r requirements/production.txt
    autoDeploy: true
    startCommand: sh -c "python manage.py migrate --noinput && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:$PORT"
